services:
  frontend:
    build: .
    container_name: vite-react-app
    ports:
      - "5173:5173"  # Vite dev server runs on port 5173
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0  # <-- Add --host 0.0.0.0 to expose to all network interfaces
