version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    command: npm run dev -- --host 0.0.0.0
    networks:
      - app-network

  app:
    build:
      context: ./model
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./model/.env
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  node-app:
    build:
      context: ./backend
    container_name: node-app
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
