services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  # Your Node.js application
  app:
    build: .
    container_name: node-app
    env_file:
      - .env 
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
