apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: capstone2user/node-app:1.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: my-app
spec:
  type: ClusterIP
  selector:
    app: node-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
